---
title: "Assignment 1 ST302"
author: "your name"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F)


```





## Question 1. 



## Question 2



a. 
    
b. 

## Question 3


Packages you will need. You only need the install once only. After that delete this code block.
```{r, eval=FALSE}
install.packages("tidyverse") # do not need this on server
install.packages("lubridate") # do not need this on server
install.packages("here")
```

```{r, echo=TRUE}
library(tidyverse)
water <- read_csv(here::here("hwk", "Data","BathingWaterQuality2013.csv"))
water <- mutate(water,Date= lubridate::dmy(Date))
water4 <- filter(water, Beach %in% c("Sutton", "Portmarnock" ,"Skerries" ,"Howth - Claremont"))


```

a. 
```{r}

```

b. 
```{r}

```

c. 
```{r}

```

d. 
```{r}

```

e. 

f. 
```{r}

```

g. 
```{r}

```

h. 
```{r}

```

i. 

```{r}

```


## Question 4

a.
```{r,  out.width="50%", fig.show='hold'}

```

b.
```{r,  out.width="50%", fig.show='hold'}

```


c.
```{r}

```

d.

